jobs:
  notify:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        ACTION_NAME: ${{ github.event.action }}
        REPO_URL: ${{ github.event.repository.html_url }}
        VERSION: ${{ github.event.release.html_url }}
        WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_WEBHOOK_URL }}
      name: Run webhook curl command
      run: curl -s POST "$WEBHOOK_URL" -H "Content-Type:application/json" --data '{"action":"'$ACTION_NAME'",
        "repo":"'$REPO_URL'", "version":"'$VERSION'"}'
      shell: bash
name: Notify Android SDK Release
on:
  repository_dispatch:
    types: trigger-ga___notify_release.yml
