jobs:
  notify:
    if: ${{ !github.event.issue.pull_request && (github.event.issue.state == 'closed'
      || contains(github.event.issue.labels.*.name, 'pending-response') || contains(github.event.issue.labels.*.name,
      'closing-soon-if-no-response')) }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        BODY: ${{ toJson(github.event.comment.body) }}
        COMMENT_URL: ${{ github.event.comment.html_url }}
        WEBHOOK_URL: ${{ secrets.SLACK_COMMENT_WEBHOOK_URL }}
      name: Run webhook curl command
      run: echo $BODY | xargs -I {} curl -s POST "$WEBHOOK_URL" -H "Content-Type:application/json"
        --data '{"issue":"'$COMMENT_URL'", "body":"{}"}'
      shell: bash
name: Notify Comments on PCR
on:
  repository_dispatch:
    types: trigger-ga___notify_comments.yml
