jobs:
  snapshot-release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.SNAPSHOT_PUBLISHER_ROLE }}
    - continue-on-error: true
      name: Start Snapshot Release
      uses: aws-actions/aws-codebuild-run-build@f202c327329cbbebd13f986f74af162a8539b5fd
      with:
        project-name: AndroidSDK-SnapshotRelease
name: Android SDK Snapshot Release
on:
  repository_dispatch:
    types: trigger-ga___snapshot_release.yml
permissions:
  id-token: write
